server {
    listen 80;
    root /var/www/html/public;
    index index.php;

    # Backend Laravel API
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Frontend Vue.js
    location / {
        proxy_pass http://vue:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bdd MinIO
    location /storage/ {
        proxy_pass http://minio:9000/screenshots/;
        proxy_set_header Host $http_host;
    }

    location /app {
    proxy_pass http://soketi:6001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    }
}